name: docker-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:     
  DOCKER_BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: gradle build
        run: ./gradlew build
        
      - name: build docker image
        run: docker build -t migsking/dsm-ranking .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: migsking/dsm-ranking
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
